import type { NextPage } from 'next';
import Head from 'next/head';
import { Container, VStack } from "@chakra-ui/react";
import HeaderComponent from "../components/Header/header.component";
import CurrenciesTableComponent from "../components/CurrenciesTable/currencies-table.component";

const Home: NextPage = () => {
  return (
    <div className="">
      <Head>
        <title>Cryptocurrency, Prices, Chart And Market ...</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Container maxW="container.xl">
        <VStack spacing="20px">
          <HeaderComponent />
          <CurrenciesTableComponent />
        </VStack>
      </Container>
    </div>
  )
}

export default Home
